{
 "title": "pinger",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "ip地址：",
    "query": "label_values(pinger_Packets_Send,ip)"
   },
   {
    "name": "interval",
    "label": "时间粒度",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "测试数与丢包数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(pinger_Packets_Send{ip=\"$ip\"}[$interval]))",
     "legendFormat": "send: {{ ip }}"
    },
    {
     "expr": "sum(delta(pinger_Packets_Recv{ip=\"$ip\"}[$interval]))",
     "legendFormat": "recv: {{ ip }}"
    },
    {
     "expr": "sum(delta(pinger_Packets_Lost{ip=\"$ip\"}[$interval]))",
     "legendFormat": "lost: {{ ip }}"
    }
   ]
  },
  {
   "title": "延迟统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pinger_Packets_Delay_sum{ip=\"$ip\"}[$interval])) /sum(rate(pinger_Packets_Delay_count{ip=\"$ip\"}[$interval]))",
     "legendFormat": "delay"
    }
   ]
  },
  {
   "title": "丢包率",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(pinger_Packets_Lost{ip=\"$ip\"} / pinger_Packets_Send{ip=\"$ip\"}) * 100"
    }
   ]
  }
 ]
}